"""add job application

Revision ID: 4cefe2dc6740
Revises: 153d5eb2350e
Create Date: 2025-11-25 15:39:58.488297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cefe2dc6740'
down_revision: Union[str, Sequence[str], None] = '153d5eb2350e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('job_posts', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.execute("UPDATE job_posts SET is_open = true")
    op.alter_column('job_posts', 'is_open', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'is_open')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
